### ISSUE TITLE
Practica 6

### ISSUE THREAD

**Issue by AxayacatlS** [SistemasTecTlaxiaco/diseno-de-interactividad-de-la-realidad-aumentada-equipo-axayacatl#1]
[Practica 6 Interactividad de Objetos 3D.pdf](https://github.com/SistemasTecTlaxiaco/diseno-de-interactividad-de-la-realidad-aumentada-equipo-axayacatl/files/6384168/Practica.6.Interactividad.de.Objetos.3D.pdf)

**Comment by ElvisS10** [comment]
**Calificación:** 20% Muy bien trabajo compañeros 👍

**Comment by josealfredo79** [comment]
Bien hecho y revisado.
